title: Canon Printer Installation for Windows/MAC 
description: Visit Canon.com/ijsetup and enter the printer model number you want to get. Install it on your windows or mac device using the simple steps given here.
theme: jekyll-theme-cayman
